apiVersion: apps/v1
kind: Deployment
metadata:
  name: total bike list
  labels:
    app: total bike list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: total bike list
  template:
    metadata:
      labels:
        app: total bike list
    spec:
      containers:
        - name: total bike list
          image: username/total bike list:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
